# This file was generated by GoReleaser. DO NOT EDIT.
cask "thinkt" do
  name "thinkt"
  desc "Tools for exploring LLM conversation traces"
  homepage "https://github.com/wethinkt/go-thinkt"
  version "0.3.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "thinkt"
  manpage "man/man1/thinkt-completion-bash.1"
  manpage "man/man1/thinkt-completion-fish.1"
  manpage "man/man1/thinkt-completion-powershell.1"
  manpage "man/man1/thinkt-completion-zsh.1"
  manpage "man/man1/thinkt-completion.1"
  manpage "man/man1/thinkt-projects-copy.1"
  manpage "man/man1/thinkt-projects-delete.1"
  manpage "man/man1/thinkt-projects-summary.1"
  manpage "man/man1/thinkt-projects.1"
  manpage "man/man1/thinkt-prompts-extract.1"
  manpage "man/man1/thinkt-prompts-info.1"
  manpage "man/man1/thinkt-prompts-list.1"
  manpage "man/man1/thinkt-prompts-templates.1"
  manpage "man/man1/thinkt-prompts.1"
  manpage "man/man1/thinkt-serve-lite.1"
  manpage "man/man1/thinkt-serve-mcp.1"
  manpage "man/man1/thinkt-serve.1"
  manpage "man/man1/thinkt-sessions-copy.1"
  manpage "man/man1/thinkt-sessions-delete.1"
  manpage "man/man1/thinkt-sessions-list.1"
  manpage "man/man1/thinkt-sessions-summary.1"
  manpage "man/man1/thinkt-sessions-view.1"
  manpage "man/man1/thinkt-sessions.1"
  manpage "man/man1/thinkt-sources-list.1"
  manpage "man/man1/thinkt-sources-status.1"
  manpage "man/man1/thinkt-sources.1"
  manpage "man/man1/thinkt-theme-builder.1"
  manpage "man/man1/thinkt-theme-list.1"
  manpage "man/man1/thinkt-theme-set.1"
  manpage "man/man1/thinkt-theme.1"
  manpage "man/man1/thinkt-tui.1"
  manpage "man/man1/thinkt.1"
  bash_completion "completions/thinkt.bash"
  zsh_completion "completions/thinkt.zsh"
  fish_completion "completions/thinkt.fish"

  on_macos do
    on_intel do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/go-thinkt_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "7241a010a4e27afc1085ff7e9085395c9a736241dc82d98d99d3027d06471c81"
    end
    on_arm do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/go-thinkt_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "1c39f3c35eb01abca95c73a7772a3c0c314aa29b3e683b425c09f89b95690394"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/go-thinkt_#{version}_linux_amd64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "735df003b62509e2dd13c3467db897b114e7542ac14a05b2a06415d80727bd91"
    end
    on_arm do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/go-thinkt_#{version}_linux_arm64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "fffe708f1570ff10be8cafc576cae5847986debd201b36d20a6048cedb11be6b"
    end
  end

  # No zap stanza required
end
