# This file was generated by GoReleaser. DO NOT EDIT.
cask "thinkt-indexer" do
  name "thinkt-indexer"
  desc "Tools for exploring LLM conversation traces"
  homepage "https://github.com/wethinkt/go-thinkt"
  version "0.6.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "thinkt-indexer"

  on_macos do
    on_intel do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/thinkt-indexer_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "659dfc86dc7ea5dfffb0f90bae7fb19a76d96cfda81bf0852571e3fcebfba6c6"
    end
    on_arm do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/thinkt-indexer_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "8bc803e79fb4a03e10674a38afe683f41152aa714e47ae783863051b2d7f9f34"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/thinkt-indexer_#{version}_linux_amd64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "0a88aef86b2f9c08dc0c0342692cdb49574243e4c7ddb0a8f13a58630d9f4b01"
    end
    on_arm do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/thinkt-indexer_#{version}_linux_arm64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "1d3c90177547bd0c751411ae8dce2003c3f886b3470ea0c418327f8fc266a6d9"
    end
  end

  # No zap stanza required
end
