# This file was generated by GoReleaser. DO NOT EDIT.
cask "thinkt-indexer" do
  name "thinkt-indexer"
  desc "Tools for exploring LLM conversation traces"
  homepage "https://github.com/wethinkt/go-thinkt"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "thinkt-indexer"

  on_macos do
    on_intel do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/thinkt-indexer_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "43009dbaece0505bc70afa33c6248908656d8c7814bac7a37535689b64ad40b5"
    end
    on_arm do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/thinkt-indexer_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "919868d7eec99d46c1d456f634245684ee2fb01d1432ded714dac19437d739c2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/thinkt-indexer_#{version}_linux_amd64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "05e668e8cef36cadea6b977f5945332a2478383143413210fefe079c1f6a1acf"
    end
    on_arm do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/thinkt-indexer_#{version}_linux_arm64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "63612bc5e111b955442693e22ed22bcbf6e0ef901322425743ce6337fe29adc9"
    end
  end

  # No zap stanza required
end
