# This file was generated by GoReleaser. DO NOT EDIT.
cask "thinkt" do
  name "thinkt"
  desc "Tools for exploring LLM conversation traces"
  homepage "https://github.com/wethinkt/go-thinkt"
  version "0.2.27"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "thinkt"
  manpage "man/man1/thinkt.1"
  bash_completion "completions/thinkt.bash"
  zsh_completion "completions/thinkt.zsh"
  fish_completion "completions/thinkt.fish"

  on_macos do
    on_intel do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/go-thinkt_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "bb5d788d8df542448abd233668f67a3a46a362283124214916534973d1f8b145"
    end
    on_arm do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/go-thinkt_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "2c20a353c674cdae4b76b5dadad2e24dd50480b228cc859a512a817b934d4fb3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/go-thinkt_#{version}_linux_amd64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "45c84a8bf5e237b925002fe5ef00c1c9c60d2ddc7ac940646fe0572dea072b12"
    end
    on_arm do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/go-thinkt_#{version}_linux_arm64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "57d6e8d6b708a0d84cc88f80c7c1592cdbff456cb6bdeb0a5f4dd8fbf23c7637"
    end
  end

  # No zap stanza required
end
