# This file was generated by GoReleaser. DO NOT EDIT.
cask "thinkt" do
  name "thinkt"
  desc "Tools for exploring LLM conversation traces"
  homepage "https://github.com/wethinkt/go-thinkt"
  version "0.2.32"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "thinkt"
  manpage "man/man1/thinkt-completion-bash.1"
  manpage "man/man1/thinkt-completion-fish.1"
  manpage "man/man1/thinkt-completion-powershell.1"
  manpage "man/man1/thinkt-completion-zsh.1"
  manpage "man/man1/thinkt-completion.1"
  manpage "man/man1/thinkt-projects-copy.1"
  manpage "man/man1/thinkt-projects-delete.1"
  manpage "man/man1/thinkt-projects-summary.1"
  manpage "man/man1/thinkt-projects.1"
  manpage "man/man1/thinkt-prompts-extract.1"
  manpage "man/man1/thinkt-prompts-info.1"
  manpage "man/man1/thinkt-prompts-list.1"
  manpage "man/man1/thinkt-prompts-templates.1"
  manpage "man/man1/thinkt-prompts.1"
  manpage "man/man1/thinkt-serve-lite.1"
  manpage "man/man1/thinkt-serve-mcp.1"
  manpage "man/man1/thinkt-serve.1"
  manpage "man/man1/thinkt-sessions-copy.1"
  manpage "man/man1/thinkt-sessions-delete.1"
  manpage "man/man1/thinkt-sessions-list.1"
  manpage "man/man1/thinkt-sessions-summary.1"
  manpage "man/man1/thinkt-sessions-view.1"
  manpage "man/man1/thinkt-sessions.1"
  manpage "man/man1/thinkt-sources-list.1"
  manpage "man/man1/thinkt-sources-status.1"
  manpage "man/man1/thinkt-sources.1"
  manpage "man/man1/thinkt-theme-builder.1"
  manpage "man/man1/thinkt-theme-list.1"
  manpage "man/man1/thinkt-theme-set.1"
  manpage "man/man1/thinkt-theme.1"
  manpage "man/man1/thinkt-tui.1"
  manpage "man/man1/thinkt.1"
  bash_completion "completions/thinkt.bash"
  zsh_completion "completions/thinkt.zsh"
  fish_completion "completions/thinkt.fish"

  on_macos do
    on_intel do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/go-thinkt_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "e5f12b51bdd0b00b2705f07b76ce00d5dda8155d723cc8c2eea7304b3310f20e"
    end
    on_arm do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/go-thinkt_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "b5df1532f5ffd64870fbe36c852db53045715b397ed753b61eeaff79200ba736"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/go-thinkt_#{version}_linux_amd64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "f5fa1a44811f2ecef0a53e5d366d40b8067d2c12c3e8b468b8796753b61b7268"
    end
    on_arm do
      url "https://github.com/wethinkt/go-thinkt/releases/download/v#{version}/go-thinkt_#{version}_linux_arm64.tar.gz",
        verified: "github.com/wethinkt/go-thinkt"
      sha256 "a430065179ca1bf51c261b1a704db7162a7ace3a92bc840c90a7b73a1e74198f"
    end
  end

  # No zap stanza required
end
